=== cmu-sei/Gameboard/src/Gameboard.Api.GamebrainSchemaGenerator/schemata/game-engine-state.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "GameEngineGameState",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "id",
    "name",
    "managerId",
    "managerName",
    "markdown",
    "launchpointUrl",
    "isActive",
    "players",
    "whenCreated",
    "startTime",
    "endTime",
    "expirationTime",
    "vms",
    "challenge"
  ],
  "properties": {
    "id": {
      "type": "string",
      "minLength": 1
    },
    "name": {
      "type": "string",
      "minLength": 1
    },
    "managerId": {
      "type": "string",
      "minLength": 1
    },
    "managerName": {
      "type": "string",
      "minLength": 1
    },
    "markdown": {
      "type": "string",
      "minLength": 1
    },
    "audience": {
      "type": [
        "null",
        "string"
      ]
    },
    "launchpointUrl": {
      "type": "string",
      "minLength": 1
    },
    "isActive": {
      "type": "boolean"
    },
    "players": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/GameEnginePlayer"
      }
    },
    "whenCreated": {
      "type": "string",
      "format": "date-time",
      "minLength": 1
    },
    "startTime": {
      "type": "string",
      "format": "date-time",
      "minLength": 1
    },
    "endTime": {
      "type": "string",
      "format": "date-time",
      "minLength": 1
    },
    "expirationTime": {
      "type": "string",
      "format": "date-time",
      "minLength": 1
    },
    "vms": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/GameEngineVmState"
      }
    },
    "challenge": {
      "$ref": "#/definitions/GameEngineChallengeView"
    }
  },
  "definitions": {
    "GameEnginePlayer": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "gamespaceId",
        "subjectId",
        "subjectName",
        "permission",
        "isManager"
      ],
      "properties": {
        "gamespaceId": {
          "type": "string",
          "minLength": 1
        },
        "subjectId": {
          "type": "string",
          "minLength": 1
        },
        "subjectName": {
          "type": "string",
          "minLength": 1
        },
        "permission": {
          "$ref": "#/definitions/GameEnginePlayerPermission"
        },
        "isManager": {
          "type": "boolean"
        }
      }
    },
    "GameEnginePlayerPermission": {
      "type": "string",
      "description": "",
      "x-enumNames": [
        "None",
        "Editor",
        "Manager"
      ],
      "enum": [
        "None",
        "Editor",
        "Manager"
      ]
    },
    "GameEngineVmState": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "name",
        "isolationId",
        "isRunning",
        "isVisible"
      ],
      "properties": {
        "id": {
          "type": "string",
          "minLength": 1
        },
        "name": {
          "type": "string",
          "minLength": 1
        },
        "isolationId": {
          "type": "string",
          "minLength": 1
        },
        "isRunning": {
          "type": "boolean"
        },
        "isVisible": {
          "type": "boolean"
        }
      }
    },
    "GameEngineChallengeView": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "maxPoints",
        "maxAttempts",
        "attempts",
        "score",
        "sectionCount",
        "sectionIndex",
        "sectionScore",
        "lastScoreTime",
        "questions"
      ],
      "properties": {
        "text": {
          "type": [
            "null",
            "string"
          ]
        },
        "maxPoints": {
          "type": "integer",
          "format": "int32"
        },
        "maxAttempts": {
          "type": "integer",
          "format": "int32"
        },
        "attempts": {
          "type": "integer",
          "format": "int32"
        },
        "score": {
          "type": "number",
          "format": "double"
        },
        "sectionCount": {
          "type": "integer",
          "format": "int32"
        },
        "sectionIndex": {
          "type": "integer",
          "format": "int32"
        },
        "sectionScore": {
          "type": "number",
          "format": "double"
        },
        "sectionText": {
          "type": [
            "null",
            "string"
          ]
        },
        "lastScoreTime": {
          "type": "string",
          "format": "date-time",
          "minLength": 1
        },
        "questions": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/GameEngineQuestionView"
          }
        }
      }
    },
    "GameEngineQuestionView": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "answer",
        "isCorrect",
        "isGraded",
        "penalty",
        "text",
        "weight"
      ],
      "properties": {
        "answer": {
          "type": "string",
          "minLength": 1
        },
        "example": {
          "type": [
            "null",
            "string"
          ]
        },
        "hint": {
          "type": [
            "null",
            "string"
          ]
        },
        "isCorrect": {
          "type": "boolean"
        },
        "isGraded": {
          "type": "boolean"
        },
        "penalty": {
          "type": "number",
          "format": "float"
        },
        "text": {
          "type": "string",
          "minLength": 1
        },
        "weight": {
          "type": "number",
          "format": "float"
        }
      }
    }
  }
}

=== cmu-sei/Gameboard/src/Gameboard.Tests.Unit/Assets/test-topo-state.json
{
    "id": "75da686f-4d37-48cb-8755-80121ebf3647",
    "name": "BenState",
    "managerId": "7fb2c8d6-c83f-412e-8e18-0e87ed3befcc",
    "managerName": "Sergei",
    "markdown": "Here is some markdown _stuff_.",
    "audience": "gameboard",
    "launchpointUrl": "https://google.com",
    "players": [
        {
            "gamespaceId": "33b9cf31-8686-4d95-b5a8-9fb1b7f8ce71",
            "subjectId": "f4390dff-420d-47da-90c8-4c982eeab822",
            "subjectName": "A cool player",
            "permission": "None",
            "isManager": true
        }
    ],
    "whenCreated": "2023-02-24T14:37:17.303135-05:00",
    "startTime": "2023-02-24T14:37:17.319478-05:00",
    "endTime": "2023-02-24T15:37:17.319492-05:00",
    "expirationTime": "2023-02-24T15:37:17.319507-05:00",
    "isActive": true,
    "vms": [
        {
            "id": "10fccb66-6916-45e2-9a39-188d3a692d4a",
            "name": "VM 1",
            "isolationId": "vm1",
            "isRunning": true,
            "isVisible": true
        },
        {
            "id": "8d771689-8b37-48e7-b706-9efe1c64bdca",
            "name": "VM 2",
            "isolationId": "vm2",
            "isRunning": true,
            "isVisible": false
        }
    ],
    "challenge": {
        "text": "A challenging challenge",
        "maxPoints": 100,
        "maxAttempts": 3,
        "attempts": 1,
        "score": 50,
        "sectionCount": 1,
        "sectionIndex": 0,
        "sectionScore": 50,
        "sectionText": "The best one",
        "lastScoreTime": "2023-02-24T14:42:17.319688-05:00",
        "questions": [
            {
                "text": "What is your quest?",
                "hint": "It\u0027s not about swallows or whatever",
                "answer": "swallows",
                "example": "To be the very best, like no one ever was",
                "weight": 0.5,
                "penalty": 0.2,
                "isCorrect": false,
                "isGraded": true
            }
        ]
    }
}
